language: node_js

node_js:
  - 7
sudo: false

cache:
  directories:
    - node_modules

env:
  global:
    - GIT_COMMITTER_NAME=Hiroshi Urabe
    - GIT_COMMITTER_EMAIL=mail@torounit.com
    - GIT_AUTHOR_NAME=Hiroshi Urabe
    - GIT_AUTHOR_EMAIL=mail@torounit.com

before_script:
  - npm install
script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master